apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
